name: Handpresse.com
favicon: null
layout_spectrum: 0.2624
typography_spectrum: 0.99393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e8e5d5'
    - '#f3f2ea'
    - '#fe2400'
    - '#feaea1'
  brandStrength: 0.8125
  lightness: 0.1395983686670661
  saturation: 0.6966508729383349
  rhythmicContrast: 0.9631404776591808
purpose: []
